#!/usr/bin/env python
# coding=utf-8
CONSTANT_ACTION={}
CONSTANT_ACTION_SCORE=[]
CONSTANT_ACTION['CONS_ACTION_MEETING']=u'APPLY_MEETING'
CONSTANT_ACTION['CONS_ACTION_MEETING_SCORE']=15

CONSTANT_ACTION['CONS_ACTION_COLLECT']=u'COLLECT_PROJECT'
CONSTANT_ACTION['CONS_ACTION_COLLECT_SCORE']=10

CONSTANT_ACTION['CONS_ACTION_DETAIL']=u'PROJECT_DETAIL'
CONSTANT_ACTION['CONS_ACTION_DETAIL_SCORE']=5

CONSTANT_ACTION['CONS_ACTION_VIEW']=u'PROJECT_VIEW'
CONSTANT_ACTION['CONS_ACTION_VIEW_SCORE']=5


CONSTANT_ACTION['CONS_ACTION_BP']=u'PROJECT_BP'
CONSTANT_ACTION['CONS_ACTION_BP_SCORE']=5


CONSTANT_ACTION['CONS_ACTION_EXPOSE']=u'PROJECT_EXPOSE'
CONSTANT_ACTION['CONS_ACTION_EXPOSE_SCORE']=0
ACTION_WEIGHT = {
    'APPLY_MEETING':15,
    'COLLECT_PROJECT':10,
    #'PROJECT_DETAIL':5,
    'PROJECT_VIEW':5,
    'PROJECT_BP':5
    #'PROJECT_EXPOSE':5
}
TRAIN_PARAMS = {
    'TRAIN_TIMEOUT_EXIT':50*5,
    'FLUSH_TIMEOUT_EXIT':50,
    #'RUN_TIMEOUT_EXIT':5,
    'RUN_TIMEOUT_EXIT':600,
    #'TRAIN_LIMIT_RUN':100000,
    'TRAIN_LIMIT_RUN':50000,
    #'TRAIN_LIMIT_DOOR':2600000,
    'TRAIN_LIMIT_DOOR':250000,
    'FLUSH_LIMIT_DOOR':20000,
    #'FLUSH_LIMIT_DOOR':2600000,
    'RUN_LIMIT_DOOR':10000,
    'RUN_LIMIT_RUN':100000
}
RECOM_PARAMS = {
    'NB_TOPK_NUM':50,
    'RECOM_PROJECTS_TOPK_NUM':50
}
SIM_PARAMS = {
    'SIM_THRESHOLD':0.044
}
CONST_USER_LIST='userIdList'

